### ISSUE TITLE
GNOME 3.16 compatibility

### ISSUE THREAD

**Issue by rhertzog** [olebowle/gnome-shell-timer#28]
The current release does not advertise GNOME 3.16 compatibility. I have not yet tried to run the current codebase under GNOME 3.16 but it would be nice if we could have a new release working with GNOME 3.16.

**Comment by olebowle** [comment]
I'm not exactly comfortable with releasing an untested version. As I'm not using GNOME Shell anymore, it be nice if someone could test the extension with 3.16. If it is working properly, I'll surley add the new release.

**Comment by rhertzog** [comment]
I just tested it and it seems to work fine.

**Comment by olebowle** [comment]
BTW: I also added [signatures](https://github.com/olebowle/gnome-shell-timer/releases/tag/v0.3.16) for the current release.
